### ISSUE TITLE
java.lang.NoSuchMethodError: com.musicg.wave.extension.Spectrogram.getSpectrogramData()

### ISSUE THREAD

**Issue by GoogleCodeExporter** [neurobin/musicg#1]
```
Tried to run the RenderSpectrogramDemo but I got an error. It seems that a 
method is missing from the class Spectrogram. 

See below for details. 

Exception in thread "main" java.lang.NoSuchMethodError: 
com.musicg.wave.extension.Spectrogram.getSpectrogramData()[[D
    at com.musicg.graphic.GraphicRender.renderSpectrogram(GraphicRender.java:138)
    at RenderSpectrogramDemo.main(RenderSpectrogramDemo.java:39)



```

Original issue reported on code.google.com by `Albert.L...@gmail.com` on 19 Sep 2012 at 3:27

**Comment by GoogleCodeExporter** [comment]
```
I ran into a similar issue. The way I figured out how to move around it - at 
least until the issues is addressed - was to circumvent that particular call 
and do what the constructor was intended to do. 

After you create your Spectrogram instance, you need to create a double array, 
as that is what the GraphicRender is expecting when you are passing data using 
renderSpecrogramData.

For example:
Spectrogram spectrogram1 = new Spectrogram(audio1);
double [][] spec1Data = spectrogram1.getAbsoluteSpectrogramData();
GraphicRender render = new GraphicRender();
render.renderSpectrogramData(spec1Data, "spec1.jpg");

That got me the spectrogram that I was looking for.
```

Original comment by `green.jo...@gmail.com` on 9 Nov 2012 at 1:59

**Comment by jnisperuza** [comment]
Hola a todos, comenzando un trabajo de investigacion de la universidad me encontré con este maravilloso proyecto, el cual presenta un inconveniente en su ejemplo: RenderSpectrogramDemo, el cual no genera el espectograma, depués de analizar y modificar el código de la API logré solucionar el inconveniente.
[musicg-google](http://escribojava.blogspot.com.co/2017/04/musicg-google.html)

**Comment by jnisperuza** [comment]
Hola a todos, comenzando un trabajo de investigacion de la universidad me encontré con este maravilloso proyecto, el cual presenta un inconveniente en su ejemplo: RenderSpectrogramDemo, el cual no genera el espectograma, depués de analizar y modificar el código de la API logré solucionar el inconveniente.
[musicg-google](http://escribojava.blogspot.com.co/2017/04/musicg-google.html)
